# Generated by Django 2.1.1 on 2018-09-18 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='suggestion_model',
            new_name='SuggestionModel',
        ),
    ]
